development:
  adapter: mysql
  encoding: utf8
  database: media-thinger_development
  pool: 5
  username: root
  password:
  socket: /opt/local/var/run/mysql5/mysqld.sock

test:
  adapter: mysql
  encoding: utf8
  database: media-thinger_test
  pool: 5
  username: root
  password:
  socket: /opt/local/var/run/mysql5/mysqld.sock

production:
  adapter: mysql
  encoding: utf8
  database: media-thinger_production
  pool: 5
  username: root
  password:
  socket: /var/run/mysqld/mysqld.sock
